version: "3"

services:
  db:
    ports:
      - ${MYSQL_PORT:-3306}:3306

  phpmyadmin:
    # container_name: pma
    image: phpmyadmin/phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      VIRTUAL_HOST: ${PHPMYADMIN_HOST}
      LETSENCRYPT_HOST: ${PHPMYADMIN_HOST}
    restart: always
    ports:
      - ${PHPMYADMIN_PORT:-3030}:80
    networks:
      - default
      - proxy
